#!/bin/sh

[ -r /etc/sysconfig/i18n ] && . /etc/sysconfig/i18n
export LANG
export SYSFONT
vncconfig -iconic &
# unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid lightblue
xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
exec /bin/sh /etc/xdg/xfce4/xinitrc
